apiVersion: v1
kind: Namespace
metadata:
  name: strapi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi
  namespace: strapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      containers:
        - name: strapi
          env:
          - name: DATABSE_CLIENT
            value: "postgres"
          - name: DATABASE_PORT
            value: "5432"
          - name: DATABASE_NAME
            value: "strapi"
          - name: DATABASE_USERNAME
            value: "strapi"
          - name: DATABASE_PASSWORD
            value: "strapi"
          - name: strapi
          image: ghcr.io/sometea/hobbymusik-strapi:latest
          ports:
          - containerPort: 1337

---
apiVersion: v1
kind: Service
metadata:
  name: strapi-service
  namespace: strapi
spec:
  selector:
    app: strapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1337
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: strapi
  namespace: strapi
spec:
  rules:
    - http:
        paths:
          - path: /strapi
            pathType: Prefix
            backend:
              service:
                name: strapi-service
                port:
                  number: 80