apiVersion: v1
kind: Namespace
metadata:
  name: strapi

---
apiVersion: v1
kind: Secret
metadata:
  name: strapi-secrets
  namespace: strapi
type: Opaque
stringData:
  DATABASE_USERNAME: "strapi"
  DATABASE_PASSWORD: "strapi"
  APP_KEYS: "toBeModified1,toBeModified2"
  JWT_SECRET: "toBeModified3"
  API_TOKEN_SALT: "toBeModified4"
  ADMIN_JWT_SECRET: "toBeModified5"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: strapi-pvc
  namespace: strapi
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: strapi
  namespace: strapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: strapi
  template:
    metadata:
      labels:
        app: strapi
    spec:
      containers:
        - name: strapi
          env:
          - name: DATABASE_CLIENT
            value: "postgres"
          - name: DATABASE_PORT
            value: "5432"
          - name: DATABASE_HOST
            value: "postgres.default.svc.cluster.local"
          - name: DATABASE_NAME
            value: "strapi"
          - name: DATABASE_USERNAME
            valueFrom:
              secretKeyRef:
                name: strapi-secrets
                key: DATABASE_USERNAME
          - name: DATABASE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: strapi-secrets
                key: DATABASE_PASSWORD
          - name: APP_KEYS
            valueFrom:
              secretKeyRef:
                name: strapi-secrets
                key: APP_KEYS
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: strapi-secrets
                key: JWT_SECRET
          - name: API_TOKEN_SALT
            valueFrom:
              secretKeyRef:
                name: strapi-secrets
                key: API_TOKEN_SALT
          - name: ADMIN_JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: strapi-secrets
                key: ADMIN_JWT_SECRET
          image: ghcr.io/sometea/hobbymusik-strapi:latest
          ports:
          - containerPort: 1337
          volumeMounts:
            - name: strapi-data
              mountPath: /opt/app/public/uploads
      volumes:
        - name: strapi-data
          persistentVolumeClaim:
            claimName: strapi-pvc
      nodeSelector:
        kubernetes.io/hostname: devplatform01    
---
apiVersion: v1
kind: Service
metadata:
  name: strapi-service
  namespace: strapi
spec:
  selector:
    app: strapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 1337
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: strapi
  namespace: strapi
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: strapi-service
                port:
                  number: 80